MODULES = jailed
include $(THEOS)/makefiles/common.mk

TWEAK_NAME = yalu101
DISPLAY_NAME = yalu101
BUNDLE_ID = com.f0xnine.org

yalu101_USE_FISHHOOK = 1
yalu101_FILES = Tweak.xm
yalu101_IPA = ../mach_portal+yalu-b3.ipa

include $(THEOS_MAKE_PATH)/tweak.mk
